import pyautogui
import time

print("time to rock...")
print("open the browser (ill only give you 2 seconds)")
time.sleep(2) # to give time to open the browser
pyautogui.hotkey("enter")
time.sleep(35)
pyautogui.write("f")
time.sleep(5)
pyautogui.write("j")
time.sleep(22)
pyautogui.write("fdsajkl;fdsajkl;")
time.sleep(13)
pyautogui.write(" ")
time.sleep(7.7)
pyautogui.write("a as ask asks all")
time.sleep(0.3)
pyautogui.write("ask dad; ask dad;")
time.sleep(3.75)
pyautogui.write("a salad flask")
time.sleep(0.3)
pyautogui.write("a lass falls")
time.sleep(27.7)
pyautogui.write("h")
time.sleep(3.2)
pyautogui.write("g")
time.sleep(12)
pyautogui.write("a;sldkf jgh")
time.sleep(4.7)
pyautogui.write("fdsafgf jkl;jhj")
time.sleep(2)
pyautogui.write("a as has had")
time.sleep(6)
pyautogui.write("dash dash dash dash")
time.sleep(9.3)
pyautogui.write("dad had a glad lad")
time.sleep(12)
pyautogui.write("sh ash dash gash hash lash")
time.sleep(2.5)
pyautogui.write("a flash lass had a glass")
time.sleep(4.3)
pyautogui.write("all fall hall all fall hall")
time.sleep(6)
pyautogui.write("dad had a salad")
time.sleep(10)
pyautogui.write("a lad had a flag")
time.sleep(5)
pyautogui.write("dad had half a glass")
time.sleep(41)
pyautogui.click(997, 647)
print("we're done rocking")